FROM ruby:2.5

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - \
        && apt-get install -y nodejs --no-install-recommends && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y mysql-client sqlite3 --no-install-recommends && rm -rf /var/lib/apt/lists/

ENV RAILS_VERSION 5.2.2

RUN gem install rails --version "$RAILS_VERSION"

WORKDIR /app